language: csharp

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003133
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003133
      mono: none
      env: DOTNETCORE=1
    
script:  
  - dotnet restore Candy.Core Candy.Core.Tests
  - dotnet build Candy.Core Candy.Core.Tests
  - dotnet test Candy.Core.Tests
  