language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: osx
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121
    
script:  
  - dotnet restore Candy.Core Candy.Core.Tests
  - dotnet build Candy.Core Candy.Core.Tests
  - dotnet test Candy.Core.Tests
  