version: 0.1.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: SKiJlKI40eavVYCKXr7LOg0BmsnXCSQmDBcwaJB9Ps1FjT93pWMDQXRRXYwhzlgB
build_script:
- cmd: dotnet restore Candy.Core Candy.Core.Tests
test_script:
- ps: >-
    (Get-Content Candy.Core\project.json) | ForEach-Object { $_ -replace '"debugType": "portable"', '"debugType": "full"' } | Set-Content Candy.Core\project.json
    (Get-Content Candy.Core.Tests\project.json) | ForEach-Object { $_ -replace '"debugType": "portable"', '"debugType": "full"' } | Set-Content Candy.Core.Tests\project.json
    dotnet restore Candy.Core Candy.Core.Tests
    dotnet test Candy.Core.Tests
    nuget install OpenCover -OutputDirectory "tools" -ExcludeVersion
    nuget install coveralls.io -OutputDirectory "tools" -ExcludeVersion
    tools\OpenCover\tools\OpenCover.Console.exe -oldstyle -register:user -target:"%ProgramFiles%\dotnet\dotnet.exe" -targetargs:"test Candy.Core.Tests" -output:coverage.xml -filter:"+[*]Candy.* -[*.Tests]* -[xunit.*]*" -skipautoprops -hideskipped:All
    tools\coveralls.io\tools\coveralls.net.exe --opencover coverage.xml